name: stepvar-demo
on:
  push:
    branches:
      - main

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: step1
        env:
          stepVar1: stepvalue1
        run: |
          echo "The value for stepvar1: $stepVar1"
      - name: echo repovar1
        run: "echo \"The value for repovar1: ${{ vars.repovar1 }}\""
        