name: firstflow
on: push
jobs:
    firstjob:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - name: welcome message
              run: echo "hello world"
            - name: list files
              run: ls
            - name: make script executable
              run: chmod +x hello.sh
            - name: running shell script
              run: ./hello.sh
            