name: my third workflow
on:
    workflow_dispatch:
        inputs:
            loglevel:
                description: 'Log Level'
                required: true
                default: 'warning'

jobs:
  ascii_job:
    runs-on: ubuntu-latest
    steps:
        - name: Checkout repo
          uses: actions/checkout@v4
        - name: list of current files
          run: ls -ltra
        - name: Run ASCII art script
          run: |
            chmod +x ascii-script.sh
            ./ascii-script.sh